# Generated by Django 4.0.3 on 2022-04-10 15:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image/'),
        ),
    ]
